<a href="https://colab.research.google.com/github/toshkumarashu/repo1/blob/master/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Deep Learning is a field in Machine Learning that deals with building and using Neural Network Models
Neural Networks mimic the functuioning of a human brain.
Neural Networks withs more than three layers are typically categorised as Deep Learning Networks

Perceptron
The perceptron is the unit for learning in an artificial neural network, A perceptron resembles a human brain cell.
A perceptron is a single cell or node in an neural network

In Deep Learning we replace slope of model with weights called as w and intercept with the bias called as b.
Weights and Biases become the parameters for a neural network.
The number of weights equals the number of inputs/features.

# Aritificial Neural Network
An ANN is a network of perceptrons. A deep neural network usually has three or more layers.
Each node has its own weights, biasesand acivation functin. Each node is connected to all the nodes in the next layer forming a dense network.
Training an ANN means determining the right values for these parameters and hyperparameters such that it maximizes the accuracy of predictions for the given use case.


# Neural Network Architecture
Input Layer
The input to Deep Learning model is usually a vector of Numeric vaues.
Vectors are usually defined using NumPy arrays. It represents the feature variables or independent variables that are used for prediction as well as training.
Hidden Layer
An ANN can have one or more hidden layers. The more the layers are the deep the network is .
Each hidden layer can have one or more nodes. Typically the node count is configureed in range 2*n. Examples are 8,16,32,64,128 etc.
A neural network is defined by the number of layers and nodes.
The output of each node in previouslayer will become the inout for every node in the current layers.
When there are more nodes and layers it ususlly results in better accuracy. As a general practice , start with small number and keep adding util an acceptable accuracy levels are obtained.

Weights and Biases
They form the basis for Deep Learning Algorithms . Weights and Biases are trainable parameters in a neural network model.
Each input for each node will have an associated weight with it.

Activation Fucntions
An activation function plays an important role in creating the output of the node in the neural network.
AN activation fucntin takes the martix output of the node and determines if and how the node will propagate information to the next layer.
The main objective of activation function is that itconvers the output to a non-linear values. They serve as a critical step in helping a neural network learn specific patterns in the data.

TanH- A TanH function normalizes the output in the range of (-1 ot +1)

ReLu- Rectified Linear Unit- A ReLu produce a zero if the output is negative. Else, it will produce the same input verbatim.

Softmax Function= This is used in the case of classification problems . It produces a vector of probabilites for each of thepossible classes in the outcomes. The class with the highes probability will be considered as the final class.
These all activation functions are added as hyperparameters in the model.

Output Layer
The output layer is the final layer in the neural netork where desired predictions are obtained.

Training a Neural Network Model
Set up and intialisation- Converting data into numeric vectors. Splitting data into training, validation and test sets.

Forward propagation-  Movement from input to hidden layer and then output layer.
Measure Accurarcy and Error

Backpropagation- If error is high, then it adusts weights and biases by the process of gradient descent to improve accurarcy.
Gradient Descent is the process of repeating the forward and backward propagation in order to reduce error and move closer to the desired model.
Batches and Epochs- 10000/10 (1000)

Validation and Testing

# **Deep Learning Example- Iris Dataset**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings("ignore")

Prepare input data for deep learining
Load data into pandas dataframe
convert the dataframe into anumy array
Scale the feature dataset
Use of onehot encoding for the largest variable
Split the dataset into training and test datasets.

Load Data and Review content

In [4]:
iris_data=pd.read_csv("iris.csv")
print(iris_data.head())

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa


In [6]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
iris_data['variety']=label_encoder.fit_transform(iris_data['variety'])
print(iris_data.head())

   sepal.length  sepal.width  petal.length  petal.width  variety
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0


Converting into numpy array

In [7]:
np_iris=iris_data.to_numpy()
print(np_iris.shape)

(150, 5)


Separate features and target variables

In [9]:
X_data=np_iris[:,0:4]
Y_data=np_iris[:,4]
print("\n Features before Scaling: \n......................")
print(X_data[:5,:])
print("\n Target before one-hot encoding :\n...................")
print(Y_data[:5])


 Features before Scaling: 
......................
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

 Target before one-hot encoding :
...................
[0. 0. 0. 0. 0.]


In [12]:
scaler=StandardScaler().fit(X_data)

# scale the nummeric freature variable
X_data=scaler.transform(X_data)

#Convert target varible as a one-hot encoded array
Y_data=tf.keras.utils.to_categorical(Y_data,3)

print("\n Features afer Scaling :\n-----------------")

print(X_data[:5,:])
print("\ntarget after one-hot encoding:\n---------------------")
print(Y_data[:5])


 Features afer Scaling :
-----------------
[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]

target after one-hot encoding:
---------------------
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [13]:
X_train,X_test,Y_train,Y_test=train_test_split(X_data,Y_data,test_size=0.10)
print("\n Train test Dimensions: \n-------------------")
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)


 Train test Dimensions: 
-------------------
(135, 4) (15, 4) (135, 3) (15, 3)


Create a Model

Number of hidden layers

Number of nodes in each layers

Activation functions

Loss function and accuracy measurements.

In [15]:
from tensorflow import keras

# Number of classes in the target variable
NB_CLASSES=3

#create a swquential model in keras
model=tf.keras.models.Sequential()

#add the first hidden layer
model.add(keras.layers.Dense(128, #Number of nodes
                             input_shape=(4,), # number of input variable
                             name="Hidden-Layer-1", # Logical name
                             activation="relu")) # activation function

# add a second hidden layer
model.add(keras.layers.Dense(128,
                            name="Hidden-Layer=2",
                            activation="relu"))
# add an output Layer with softmax function
model.add(keras.layers.Dense(NB_CLASSES,
                             name="Output-Layer",
                             activation="softmax"))
# compile the model with Loss and mertrics
model.compile(loss="categorical_crossentropy",
              metrics=["accuracy"])
# print the model summary
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ Hidden-Layer-1 (Dense)               │ (None, 128)                 │             640 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ Hidden-Layer=2 (Dense)               │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ Output-Layer (Dense)                 │ (None, 3)                   │             387 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 17,539 (68.51 KB)

 Trainable params: 17,539 (68.51 KB)

 Non-trainable params: 0 (0.00 B)